version: '3.7'

services:
  nginx:
    image: nginx:1.16.1
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/local.crt:/var/www/ssl/local.crt
      - ./conf/nginx/local.key:/var/www/ssl/local.key
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - ${PROJECT_PATH}:/var/www/html
    networks:
      - app

  php:
    # build: './dockerfile/php-fpm'
    image: dylanops/php-dev:7.4
    restart: always
    container_name: php
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php.ini
      - ${PROJECT_PATH}:/var/www/html
    networks:
      - app
    environment:
      PHP_IDE_CONFIG: 'serverName=web'
      BLACKFIRE_LOG_LEVEL: ${BLACKFIRE_LOG_LEVEL}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./data/backup:/var/backup
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      - app

  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elasticsearch
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: single-node
    networks:
      - app
networks:
  app:
    driver: bridge